function settitle() {
	echo -ne "\033]0;$@\007"
}

# Prompt
#PROMPT_COMMAND='settitle "${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}"'
#PS1='\u:\W\$> '

# Env definition
export HISTSIZE=3000
export HISTFILESIZE=6000
export HISTCONTROL=ignoreboth

# Other
complete -cf sudo
shopt -s cdspell
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s histappend
shopt -s hostcomplete
shopt -s nocaseglob
